### ISSUE TITLE
logtail crash where the application is work well

### ISSUE THREAD

**Issue by zhuangjinjin** [vogo/logtail#5]
**What happened**:
```shell
panic: listen tcp :54332: bind: address already in use

goroutine 40 [running]:
github.com/vogo/logtail.Start.func1(0xc0001e4000)
        /Users/gelnyang/go/src/github.com/vogo/logtail/logtail.go:38 +0x128
created by github.com/vogo/logtail.Start
        /Users/gelnyang/go/src/github.com/vogo/logtail/logtail.go:36 +0x11c
Error from server: Get https://192.168.131.2:10250/containerLogs/default/service-mp-3rd-capability-v20211027133959-77d5bb4c88-5qd5c/service-mp-3rd-capability-v20211027133959?follow=true&tailLines=10: dial tcp 192.168.131.2:10250: connect: connection refused
Error from server: Get https://192.168.131.2:10250/containerLogs/default/service-mp-3rd-capability-v20211027133959-77d5bb4c88-5qd5c/service-mp-3rd-capability-v20211027133959?follow=true&tailLines=10: dial tcp 192.168.131.2:10250: connect: connection refused
invalid character '"' after object key:value pair
  -cmd string
        tail command
  -ding-url string
        dingding url
  -file string
        config file
  -match-contains string
        a containing string
  -port int
        tail port (default 54321)
  -webhook-url string
        webhook url
```

**What you expected to happen**:
It work well

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zhuangjinjin** [comment]
My fault, I have written a invalid json format file. And it can't be restart

**Comment by zhuangjinjin** [comment]
My fault, I have written a invalid json format file. And it can't be restart
